/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 asteroids.gltf --transform 
Files: asteroids.gltf [50.08MB] > C:\Users\mohan\Downloads\wandering_asteroids_of_andromeda\asteroids-transformed.glb [2.09MB] (96%)
Author: ARCTIC  WOLVES™ (https://sketchfab.com/arctic.wolves)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wandering-asteroids-of-andromeda-6a8e84e0fdea43628b8b3ab85b130281
Title: Wandering Asteroids Of Andromeda
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

// Define asteroid belt positions
const ASTEROID_POSITIONS = [
  { position: [6, 1, 4], rotation: [0.602, -0.876, 0.354], scale: 0.5 },
  { position: [-8, 3, -5], rotation: [0.3, 0.5, -0.2], scale: 0.4 },
  { position: [15, -2, 15], rotation: [-0.4, 0.7, 0.1], scale: 0.6 },
  { position: [-12, 4, 12], rotation: [0.5, -0.3, 0.8], scale: 0.3 },
  { position: [20, -1, -10], rotation: [-0.2, 0.9, -0.4], scale: 0.45 },
  // Asteroid belt between Mars and Jupiter
  { position: [15, 0, 15], rotation: [0.1, 0.2, 0.3], scale: 0.35 },
  { position: [-15, 1, 15], rotation: [-0.3, 0.4, -0.1], scale: 0.4 },
  { position: [15, -1, -15], rotation: [0.4, -0.5, 0.2], scale: 0.3 },
  { position: [-15, 2, -15], rotation: [-0.2, 0.3, 0.4], scale: 0.45 },
];

export default function Model(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/asteroids-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const actionNames = Object.keys(actions);
    if (actionNames.length > 0) {
      actions[actionNames[0]].play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      {ASTEROID_POSITIONS.map((asteroidPos, index) => (
        <group
          key={index}
          name={`Sketchfab_Scene_${index}`}
          scale={0.04}
          position={asteroidPos.position}
        >
          <group
            name={`RootNode_${index}`}
            rotation={asteroidPos.rotation}
            scale={asteroidPos.scale}
          >
            <group
              name="AST_01_LOD0"
              position={[23.227, 0, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <group name="Object_5" position={[35.506, -49.018, -0.439]}>
                <mesh
                  name="AST_01_LOD0_Material_#48_0"
                  geometry={nodes["AST_01_LOD0_Material_#48_0"].geometry}
                  material={materials.Material_48}
                />
              </group>
            </group>
            <group name="AST_03_LOD0" position={[0, 0, 22.857]}>
              <group name="Object_8" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="AST_03_LOD0__AST_03_LOD007___Default_0"
                  geometry={
                    nodes.AST_03_LOD0__AST_03_LOD007___Default_0.geometry
                  }
                  material={materials.AST_03_LOD007___Default}
                />
              </group>
            </group>
            <group name="AST_02_LOD0">
              <group name="Object_11" rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  name="AST_02_LOD0__0"
                  geometry={nodes.AST_02_LOD0__0.geometry}
                  material={materials.AST_02_LOD0__0}
                />
              </group>
            </group>
          </group>
        </group>
      ))}
    </group>
  );
}

useGLTF.preload("/asteroids-transformed.glb");
