/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 astronaut.gltf --transform 
Files: astronaut.gltf [28.26MB] > C:\Users\mohan\Downloads\animated_astronaut_in_space_suit_loop\astronaut-transformed.glb [3.2MB] (89%)
Author: LasquetiSpice (https://sketchfab.com/LasquetiSpice)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-astronaut-in-space-suit-loop-137d62cd820a4a6eba75304a11fb6f81
Title: Animated Astronaut in Space Suit Loop
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export default function Model(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/astronaut-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  // Start the animation when component mounts
  useEffect(() => {
    // Get all animation names
    const actionNames = Object.keys(actions);
    if (actionNames.length > 0) {
      // Play the first animation
      actions[actionNames[0]].play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Sketchfab_Scene"
        position={[-5, 2, 5]} // Position the astronaut
        rotation={[0, Math.PI / 4, 0]} // Rotate to face the viewer
        scale={0.6} // Make it larger
      >
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          name="Object_102"
          geometry={nodes.Object_102.geometry}
          material={materials.material0}
          skeleton={nodes.Object_102.skeleton}
          scale={0.6}
        />
        <skinnedMesh
          name="Object_103"
          geometry={nodes.Object_103.geometry}
          material={materials.material0}
          skeleton={nodes.Object_103.skeleton}
          scale={0.6}
        />
        <skinnedMesh
          name="Object_106"
          geometry={nodes.Object_106.geometry}
          material={materials.material1}
          skeleton={nodes.Object_106.skeleton}
          scale={0.6}
        />
        <skinnedMesh
          name="Object_109"
          geometry={nodes.Object_109.geometry}
          material={materials.material2}
          skeleton={nodes.Object_109.skeleton}
          scale={0.6}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/astronaut-transformed.glb");
