/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cosmonaut.gltf --transform 
Files: cosmonaut.gltf [7.96MB] > C:\Users\mohan\Downloads\cosmonaut_on_a_rocket\cosmonaut-transformed.glb [731.22KB] (91%)
Author: Yury Misiyuk (https://sketchfab.com/Tim0)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cosmonaut-on-a-rocket-e93cbbdb9a2144fb9f63d062566f3e63
Title: Cosmonaut on a rocket
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export default function Model(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/cosmonaut-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const actionNames = Object.keys(actions);
    if (actionNames.length > 0) {
      actions[actionNames[0]].play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene" position={[6, 1, -7]} scale={0.004}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.rocket_mtl}
          skeleton={nodes.Object_7.skeleton}
        />
        <skinnedMesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials.character_mtl}
          skeleton={nodes.Object_9.skeleton}
        />
        <skinnedMesh
          name="Object_11"
          geometry={nodes.Object_11.geometry}
          material={materials.fire_mtl}
          skeleton={nodes.Object_11.skeleton}
        />
        <skinnedMesh
          name="Object_13"
          geometry={nodes.Object_13.geometry}
          material={materials.fire_mtl}
          skeleton={nodes.Object_13.skeleton}
        />
        <skinnedMesh
          name="Object_15"
          geometry={nodes.Object_15.geometry}
          material={materials.fire_mtl}
          skeleton={nodes.Object_15.skeleton}
        />
        <skinnedMesh
          name="Object_17"
          geometry={nodes.Object_17.geometry}
          material={materials.fire_mtl}
          skeleton={nodes.Object_17.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cosmonaut-transformed.glb");
